image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
  - build
  - test
  - release

variables:
  MYGET_PACKAGE_URL: "https://www.myget.org/F/finitereality/api/v2/package"

build:
  stage: build
  script:
    - dotnet build Finite.Commands.sln -c Release
    - dotnet pack Finite.Commands.sln -c Release -o artifacts
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    expire_in: 1 week
    paths:
      - artifacts/

test:
  stage: test
  script:
    - dotnet test Finite.Commands.Tests.sln -c Release

push:
  stage: release
  only:
    - master@FiniteReality/Finite.Commands
  dependencies:
    - build
  script:
    - for file in artifacts/*; do
        dotnet nuget push $file -s "$MYGET_PACKAGE_URL" -k "$MYGET_API_KEY";
      done
